controllers/auth.py
import functools
import utils.db as db   # Importamos el módulo 'utils.db' para interactuar con la base de datos

from flask import (
    Blueprint,          # Para organizar las rutas de la aplicación en un módulo
    flash,              # Para mostrar mensajes flash a los usuarios (mensajes temporales)
    g,                  # Para almacenar datos a lo largo del ciclo de la petición
    render_template,    # Para renderizar plantillas HTML
    request,            # Para acceder a los datos de la solicitud (POST, GET, etc.)
    url_for,            # Para generar URLs dinámicamente
    session,            # Para manejar la sesión del usuario
    redirect            # Para redirigir al usuario a otra página
)

# Para manejar el hashing de contraseñas
from werkzeug.security import check_password_hash, generate_password_hash  

# Definimos un blueprint llamado 'auth' con prefijo de URL '/auth'
bp = Blueprint('auth', __name__, url_prefix='/auth')

# Inicializamos el manejador de la DB para trabajar con la colección 'users'
db = db.DBHandler("users")

# Ruta para el registro de usuarios
@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username'] # Obtenemos el nombre de usuario del formulario
        password = request.form['password'] # Obtenemos la contraseña del formulario
        error = None  # Inicializamos la variable de error
        is_user_registered = db.user_exists(username)

        # Validamos si el nombre de usuario está vacío
        if not username:
            error = 'Username es requerido'
        # Validamos si la contraseña está vacía
        if not password:
            error = 'Password es requerido'

        # Si no hay errores en los campos
        if error is None:
            # Verificamos si el usuario ya está registrado
            if is_user_registered:
                flash('Username already exists. Choose a different one.', 'danger')  # Mostramos un mensaje de error
            else:
                # Registramos el usuario en la base de datos con la contraseña encriptada
                db.add_user(username, generate_password_hash(password))
                flash('Registration successful. You can now log in.', 'success')  # Mensaje de éxito

                # Redirigimos a la página de inicio de sesión
                return redirect(url_for('auth.login'))

    # Si la solicitud es GET o hubo algún error, renderizamos el formulario de registro
    return render_template('auth/register.html')

# Ruta para el inicio de sesión
@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':  # Si la solicitud es POST, se está enviando el formulario de login
        username = request.form['username']  # Obtenemos el nombre de usuario del formulario
        password = request.form['password']  # Obtenemos la contraseña del formulario
        error = None  # Inicializamos la variable de error

        # Validamos si el nombre de usuario está vacío
        if not username:
            error = 'Username es requerido'
        elif not password:
            error = 'Password es requerido'

        # Si no hay errores en los campos
        if error is None:
            # Buscamos al usuario en la base de datos por su nombre
            user = db.get_user_credentials(username)
            # Verificamos si el usuario existe y si la contraseña es correcta
            if user is None:
                error = 'Usuario no encontrado. Verifica el nombre de usuario.'  # Usuario no encontrado
            elif not check_password_hash(user["password"], password):  # Verificación de la contraseña
                error = 'Contraseña incorrecta. Inténtalo de nuevo.'

        # Si no hubo errores, iniciamos la sesión del usuario
        if error is None:
            session.clear()  # Limpiamos cualquier sesión existente
            session['user_id'] = str(user['_id'])           # Guardamos el ID del usuario en la sesión actual
            flash('Inicio de sesión exitoso.', 'success')   # Mostramos mensaje de éxito
            return redirect(url_for('todo.index'))          # Redirigimos al índice de tareas

        # Si hubo algún error, lo mostramos al usuario
        flash(error, 'danger')

    # Si la solicitud es GET o hubo algún error, renderizamos el formulario de login
    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = db.get_user_by_id(user_id)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

controllers/todo.py
from flask import (
  Blueprint,
  flash,
  g,
  redirect,
  render_template,
  request,
  url_for
)
from werkzeug.exceptions import abort

import utils.db as db
import controllers.auth as auth

bp = Blueprint('todo', __name__)
db = db.DBHandler("todo")
todos = ''

@bp.route('/')
@auth.login_required 
def index():
  todos = db.get_todo_by_user_id(g.user["_id"])
  return render_template('todo/index.html', todos=todos)

@bp.route('/create', methods=['GET', 'POST'])
@auth.login_required
def create():
  if request.method == 'POST':
    name = request.form['name']
    description = request.form['description']
    error = None

    if not description:
      error = 'Description required'

    if error is not None:
      flash(error)
    else:
        db.add_todo(name, description, False, g.user["_id"])
        return redirect(url_for('todo.index'))

  return render_template('todo/create.html')

@bp.route('/<id>/update', methods=['GET', 'POST'])
@auth.login_required
def update(id):

    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        completed = True if request.form.get('completed') == 'on' else False
        error = None

        if not name:
            error = 'Name is required.'
        if not description:
            error = 'Description is required.'

        if error is not None:
            flash(error)
        else:
            db.update_todo(id, name, description, completed, g.user["_id"])

        return redirect(url_for('todo.index'))

    if request.method == 'GET':
        todo = db.get_todo_by_id(id)
        if todo:
            return render_template(
                'todo/update.html',
                todo={
                    "name": todo["name"],
                    "description": todo["description"],
                    "completed": todo["completed"],
                    "created_at": todo["created_at"],
                    "id": id
                }
            )
        else:
            abort(404, description="Todo not found")

@bp.route('/<id>/delete', methods=['GET', 'POST'])
@auth.login_required
def delete(id):
    if request.method == 'POST':
        db.delete_todo(id, g.user["_id"])
        return redirect(url_for('todo.index'))

main.py
from flask import Flask

import utils.db as db
import utils.variables as variables

import controllers.auth as auth
import controllers.todo as todo

variables.loaded()
db = db.DBHandler("test")

def create_app():
    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY=variables.APP_SECRET_KEY,
    )

    app.register_blueprint(auth.bp)
    app.register_blueprint(todo.bp)

    @app.route('/home')
    def home():
        return '<h1> Welcome to Spendr </h1>'

    @app.route("/test-db-connection")
    def test_db_connection():
        print(db.validate_connection)
        return f"<p> {db.validate_connection()} </p>"

    return app

if __name__ == "__main__":
    print(f"~~~~>_  VERSION: {variables.VERSION}")
    app = create_app() # Create the Flask app instance
    app.run(
        debug=True, 
        host="0.0.0.0", 
        port=variables.PORT
    )

templates/layout.html
<!DOCTYPE HTML>
<title>{% block title %}{% endblock%}  - La Mixi - Todo List</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
<nav>
  <h1>La Mixi - Todo List</h1>
  <ul>
    {% if g.user %}
      <li><span>User: {{ g.user["username"] }}</span></li>
      <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Sign up</a></li>
      <li><a href="{{ url_for('auth.login') }}">Log in</a></li>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
      {% block header%}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ mesage }}</div>
  {% endfor %}
  {% block content %}{% endblock%}
</section>

templates/todo/create.html
{% extends 'layout.html' %}

{% block header %}
    <h1>{% block title %}New Todo{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <label for="name">Name</label>
        <input name="name" id="name" required />
        <label for="description">Description</label>
        <input name="description" id="description" required />
        <input type="submit" value="Save">
    </form>
{% endblock %}

templates/todo/delete.html
{% extends 'layout.html' %}

{% block header %}
    <h1>{% block title %}Update {{ todo["name"] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <label for="name">Name</label>
        <input name="name" id="name" value="{{ request.form['name'] or todo['name'] }}" required />
        <label for="description">Description</label>
        <input name="description" id="description" value="{{ request.form['description'] or todo['description'] }}" required />
        <label for="completed">Completed</label>
        <input type="checkbox" name="completed" id="completed" {% if todo["completed"] == True %}checked{% endif %} />
        <input type="submit" value="Save">
    </form>

    <form action="{{ url_for('todo.delete', id=todo['_id'] }}" method="post">
        <input type="hidden" name="delete" value="1" />
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure about delete this task?')" />
    </form>
{% endblock %}

templates/todo/index.html
{% extends 'layout.html' %}

{% block header %}
  <h1>{% block title %}To do{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('todo.create') }}">New To-do</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% if todos %}
    <ul>
      {% for todo in todos %}
        <li class="todo">
          <div>
            <h2>
              {% if todo["completed"] == True %}
                <strike>{{ todo["name"] }}</strike>
              {% else %}
                {{ todo["name"] }}
              {% endif %}
            </h2>
            <p class='description'>{{ todo["description"] }}</p
            <div class='created'>Created at: {{ todo["created_at"].strftime('%Y-%m-%d') }}</div>
            <a class='action' href="{{ url_for('todo.update', id=todo["_id"]) }}">Edit</a>
          </div>
        </li>
      {% if not loop.last %}
        <hr>
      {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>No todos found.</p>
  {% endif %}
{% endblock %}

templates/todo/update.html
{% extends 'layout.html' %}

{% block header %}
    <h1>{% block title %}Update {{ todo["name"] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <label for="name">Name</label>
        <input name="name" id="name" value="{{ request.form['name'] or todo['name'] }}" required />
        <label for="description">Description</label>
        <input name="description" id="description" value="{{ request.form['description'] or todo['description'] }}" required />
        <label for="completed">Completed</label>
        <input type="checkbox" name="completed" id="completed" {% if todo["completed"] == True %}checked{% endif %} />
        <input type="submit" value="Save">
    </form>

    <form action="{{ url_for('todo.delete', id=todo["id"]) }}" method="post">
        <input type="hidden" name="delete" value="1" />
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure about delete this task?')" />
    </form>
{% endblock %}